services:
  mongo: 
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: yourusernamehere
      MONGO_INITDB_ROOT_PASSWORD: yourpasswordhere

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: yourusernamehere
      ME_CONFIG_MONGODB_ADMINPASSWORD: yourpasswordhere
      ME_CONFIG_MONGODB_URL: mongodb://yourusernamehere:yourpasswordhere@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: yourusernamehere
      ME_CONFIG_BASICAUTH_PASSWORD: yourpasswordhere
